/**
 * Individual paint effect exports for tree-shaking optimization
 *
 * This module exports each of the 189+ 7TV paint effects as individual named exports,
 * enabling tree-shaking to include only the effects you actually use in your bundle.
 * Each effect is imported from its own individual file for optimal tree shaking.
 *
 * @fileoverview Tree-shakeable paint effect exports
 * @author Vibe Coding Team
 *
 * @example
 * // Import only the effects you need
 * import { summer, rainbow, factoryError } from '7tv-styles/effects'
 *
 * @example
 * // Use with tree-shakeable Paint component
 * import { PaintTreeShakeable as Paint } from '7tv-styles/tree-shakeable'
 * import { vaporwave } from '7tv-styles/effects'
 *
 * <Paint effectStyle={vaporwave}>Vaporwave Text</Paint>
 */

// Individual effect exports for optimal tree shaking
export { summer } from './individual/summer.js'
export { rainbow } from './individual/rainbow.js'
export { fireAndIce } from './individual/fire-and-ice.js'
export { factoryError } from './individual/factory-error.js'
export { leprechaun } from './individual/leprechaun.js'
export { firefly } from './individual/firefly.js'
export { bubblegum } from './individual/bubblegum.js'
export { eggHunt } from './individual/egg-hunt.js'
export { lollipop } from './individual/lollipop.js'
export { warmWinds } from './individual/warm-winds.js'
export { fairyGlow } from './individual/fairy-glow.js'
export { monstera } from './individual/monstera.js'
export { eightsPool } from './individual/80s-pool.js'
export { sailorsDelight } from './individual/sailors-delight.js'
export { puddle } from './individual/puddle.js'
export { honeydetected } from './individual/honeydetected.js'
export { blueberry } from './individual/blueberry.js'
export { kittyCat } from './individual/kitty-cat.js'
export { jungle } from './individual/jungle.js'
export { lobster } from './individual/lobster.js'
export { freshSoda } from './individual/fresh-soda.js'
export { farmersSky } from './individual/farmers-sky.js'
export { lavenderField } from './individual/lavender-field.js'
export { solarFlare } from './individual/solar-flare.js'
export { hippieVan } from './individual/hippie-van.js'
export { uranium } from './individual/uranium.js'
export { peacock } from './individual/peacock.js'
export { catseye } from './individual/catseye.js'
export { grapefruitSlice } from './individual/grapefruit-slice.js'
export { filmCamera } from './individual/film-camera.js'
export { copperPatina } from './individual/copper-patina.js'
export { monsteraVariegata } from './individual/monstera-variegata.js'
export { peppermint } from './individual/peppermint.js'
export { slushie } from './individual/slushie.js'
export { lifeInPlastic } from './individual/life-in-plastic.js'
export { autumnForest } from './individual/autumn-forest.js'
export { gummyWorm } from './individual/gummy-worm.js'
export { atlanticDeeps } from './individual/atlantic-deeps.js'
export { zombie } from './individual/zombie.js'
export { iceCold } from './individual/ice-cold.js'
export { slashed } from './individual/slashed.js'
export { halloweenFever } from './individual/halloween-fever.js'
export { sixties } from './individual/sixties.js'
export { berryGood } from './individual/berry-good.js'
export { present } from './individual/present.js'
export { gluhweinTime } from './individual/gluhwein-time.js'
export { sunrise } from './individual/sunrise.js'
export { fireworks } from './individual/fireworks.js'
export { hamburger } from './individual/hamburger.js'
export { pastel } from './individual/pastel.js'
export { avocado } from './individual/avocado.js'
export { penguin } from './individual/penguin.js'
export { nectarine } from './individual/nectarine.js'
export { amethyst } from './individual/amethyst.js'
export { menthol } from './individual/menthol.js'
export { swampOgre } from './individual/swamp-ogre.js'
export { heart } from './individual/heart.js'
export { raspberry } from './individual/raspberry.js'
export { cottagecore } from './individual/cottagecore.js'
export { crocus } from './individual/crocus.js'
export { luckyCharm } from './individual/lucky-charm.js'
export { potOfGold } from './individual/pot-of-gold.js'
export { nightclub } from './individual/nightclub.js'
export { easterCandy } from './individual/easter-candy.js'
export { prismatic } from './individual/prismatic.js'
export { alienPlease } from './individual/alien-please.js'
export { rabbit } from './individual/rabbit.js'
export { latteMacchiato } from './individual/latte-macchiato.js'
export { tropical } from './individual/tropical.js'
export { fantabulous } from './individual/fantabulous.js'
export { cloudy } from './individual/cloudy.js'
export { sugarMint } from './individual/sugar-mint.js'
export { chamomile } from './individual/chamomile.js'
export { hibiscus } from './individual/hibiscus.js'
export { lemonSlice } from './individual/lemon-slice.js'
export { mojito } from './individual/mojito.js'
export { breeze } from './individual/breeze.js'
export { celestial } from './individual/celestial.js'
export { aquamarine } from './individual/aquamarine.js'
export { watermelonSlice } from './individual/watermelon-slice.js'
export { citrusPunch } from './individual/citrus-punch.js'
export { creamSoda } from './individual/cream-soda.js'
export { beachBall } from './individual/beach-ball.js'
export { popsicle } from './individual/popsicle.js'
export { rhubarb } from './individual/rhubarb.js'
export { orchid } from './individual/orchid.js'
export { wisteria } from './individual/wisteria.js'
export { coralReef } from './individual/coral-reef.js'
export { pinkPrincess } from './individual/pink-princess.js'
export { corncob } from './individual/corncob.js'
export { ultraviolet } from './individual/ultraviolet.js'
export { sunflower } from './individual/sunflower.js'
export { horizon } from './individual/horizon.js'
export { bloodyMary } from './individual/bloody-mary.js'
export { skeleton } from './individual/skeleton.js'
export { candyCorn } from './individual/candy-corn.js'
export { plague } from './individual/plague.js'
export { retrovision } from './individual/retrovision-.js'
export { limoncello } from './individual/limoncello.js'
export { firebrand } from './individual/firebrand.js'
export { fallLeaves } from './individual/fall-leaves.js'
export { sourCandy } from './individual/sour-candy.js'
export { shoreline } from './individual/shoreline.js'
export { nightbloom } from './individual/nightbloom.js'
export { mistletoe } from './individual/mistletoe.js'
export { iceberg } from './individual/iceberg.js'
export { vaporwave } from './individual/vaporwave.js'
export { glazedDonut } from './individual/glazed-donut.js'
export { northStar } from './individual/north-star.js'
export { pinkLemonade } from './individual/pink-lemonade.js'
export { warlock } from './individual/warlock.js'
export { pohutukawa } from './individual/pohutukawa.js'
export { juiceBox } from './individual/juice-box.js'
export { rose } from './individual/rosé.js'
export { irishman } from './individual/irishman.js'
export { springFlowers } from './individual/spring-flowers.js'
export { radical } from './individual/radical.js'
export { friedEgg } from './individual/fried-egg.js'
export { easterEgg } from './individual/easter-egg.js'
export { pastelSky } from './individual/pastel-sky.js'
export { warmerNights } from './individual/warmer-nights.js'
export { spaceship } from './individual/spaceship.js'
export { cinder } from './individual/cinder.js'
export { sunlight } from './individual/sunlight.js'
export { pineapple } from './individual/pineapple.js'
export { cincoDeMayo } from './individual/cinco-de-mayo.js'
export { gamerGirl } from './individual/gamer-girl.js'
export { neapolitan } from './individual/neapolitan.js'
export { faintLilac } from './individual/faint-lilac.js'
export { prideMonth } from './individual/pride-month.js'
export { anodized } from './individual/anodized.js'
export { toothpaste } from './individual/toothpaste.js'
export { blossom } from './individual/blossom.js'
export { hypselodoris } from './individual/hypselodoris.js'
export { dinosaur } from './individual/dinosaur.js'
export { beachPlease } from './individual/beach-please.js'
export { friendship } from './individual/friendship.js'
export { clownfish } from './individual/clownfish.js'
export { mango } from './individual/mango.js'
export { slurpee } from './individual/slurpee.js'
export { tieDye } from './individual/tie-dye.js'
export { cocktail } from './individual/cocktail.js'
export { frutigerAero } from './individual/frutiger-aero.js'
export { seaFoam } from './individual/sea-foam.js'
export { manaPotion } from './individual/mana-potion.js'
export { ribbon } from './individual/ribbon.js'
export { strawberryCreme } from './individual/strawberry-crème.js'
export { theJoker } from './individual/the-joker.js'
export { pastelween } from './individual/pastelween.js'
export { impishBlush } from './individual/impish-blush.js'
export { hellfire } from './individual/hellfire.js'
export { cyberOptics } from './individual/cyber-optics.js'
export { fuchsia } from './individual/fuchsia.js'
export { turkeySeason } from './individual/turkey-season.js'
export { elderDragon } from './individual/elder-dragon.js'
export { divided } from './individual/divided.js'
export { kawaii } from './individual/kawaii.js'
export { wrapped } from './individual/wrapped.js'
export { glowingEmber } from './individual/glowing-ember.js'
export { eggnog } from './individual/eggnog.js'
export { jellybean } from './individual/jellybean.js'
export { frostbite } from './individual/frostbite.js'
export { roseGold } from './individual/rose-gold.js'
export { firecracker } from './individual/firecracker.js'
export { divine } from './individual/divine.js'
export { blueJay } from './individual/blue-jay.js'
export { stupidCupid } from './individual/stupid-cupid.js'
export { mochi } from './individual/mochi.js'
export { eldenLord } from './individual/elden-lord.js'
export { sunsetFizz } from './individual/sunset-fizz.js'
export { snowdrop } from './individual/snowdrop.js'
export { bouquet } from './individual/bouquet.js'
export { zestyLemon } from './individual/zesty-lemon.js'
export { cardinal } from './individual/cardinal.js'
export { forestSpring } from './individual/forest-spring.js'
export { carrotCake } from './individual/carrot-cake.js'
export { sprinkles } from './individual/sprinkles.js'
export { silverFlare } from './individual/silver-flare.js'
export { peckyChicken } from './individual/pecky-chicken.js'
export { supernova } from './individual/supernova.js'
export { nuclearWaste } from './individual/nuclear-waste.js'
export { mintyWave } from './individual/minty-wave.js'
export { sourMelon } from './individual/sour-melon.js'
export { primary } from './individual/primary.js'
export { scorched } from './individual/scorched.js'
export { enchanted } from './individual/enchanted.js'
export { atlantis } from './individual/atlantis.js'
export { unicorn } from './individual/unicorn.js'
export { tropica } from './individual/tropica.js'

// Note: For optimal tree shaking, use individual named imports:
// import { summer, rainbow } from '7tv-styles/effects'
//
// For backward compatibility with the main library, use:
// import { Paint } from '7tv-styles'
